const PREFIX_USER_ID = '/_'
const PREFIX_USER_LOGIN = '/_/'
const PREFIX_NOTE_ID = '/~/'
const PREFIX_PAGE = '/page/'
const PREFIX_AUTH = '/entry/'

const PATHNAME_BADBROWSER = 'badbrowser'
const PATHNAME_AUTH_LOGIN = 'login'
const PATHNAME_AUTH_REGISTRATION = 'registration'
const PATHNAME_AUTH_LOGOUT = 'logout'

const PATH_USER_ID = `${PREFIX_USER_ID}:userId`
const PATH_USER_LOGIN = `${PREFIX_USER_LOGIN}:userLogin`
const PATH_USER_NAME = `${PREFIX_USER_LOGIN}:userName`
const PATH_NOTE_ID = `${PREFIX_NOTE_ID}:noteId`
const PATH_BADBROWSER = `${PREFIX_PAGE}${PATHNAME_BADBROWSER}`
const PATH_AUTH_LOGIN = `${PREFIX_AUTH}${PATHNAME_AUTH_LOGIN}`
const PATH_AUTH_REGISTRATION = `${PREFIX_AUTH}${PATHNAME_AUTH_REGISTRATION}`
const PATH_AUTH_LOGOUT = `${PREFIX_AUTH}${PATHNAME_AUTH_LOGOUT}`

module.exports = {
    PREFIX_NOTE_ID,
    PREFIX_USER_ID,
    PREFIX_USER_LOGIN,
    PREFIX_PAGE,
    PREFIX_AUTH,

    PATHNAME_BADBROWSER,
    PATHNAME_AUTH_LOGIN,
    PATHNAME_AUTH_REGISTRATION,
    PATHNAME_AUTH_LOGOUT,

    PATH_NOTE_ID,
    PATH_USER_ID,
    PATH_USER_LOGIN,
    PATH_USER_NAME,
    PATH_BADBROWSER,
    PATH_AUTH_LOGIN,
    PATH_AUTH_REGISTRATION,
    PATH_AUTH_LOGOUT,
}
